Added non-clickable text component
lars-berger/GlazeWM pull request #128
Opened 2022-09-15 00:46 UTC by AgusArdizzone

Hi!

Just like the title says, i made a non-clickable text component (based on clock component).
Although it was a simple task, i'm sure there's room for improvements since i'm not a C# dev 😅

2022-09-15 07:18 UTC, lars-berger requested changes

2022-09-15 07:18 UTC, lars-berger commented on GlazeWM.Bar/Components/TextComponentViewModel.cs
> +    }
No need to call `OnPropertyChanged`, something like this should work fine:

```csharp
public class TextComponentViewModel : ComponentViewModel
{
  private TextComponentConfig _config => _componentConfig as TextComponentConfig;

  public string Text => _config.Text;

  public TextComponentViewModel(BarViewModel parentViewModel, TextComponentConfig config)
    : base(parentViewModel, config)
  {
  }
}
```

2022-09-15 07:18 UTC, lars-berger commented on GlazeWM.Bar/BarViewModel.cs
> +        TextComponentConfig tcc => new TextComponentViewModel(this,tcc),
add space after `this,`

2022-09-15 07:19 UTC, lars-berger commented
Awesome, thank you 👍 Just have some minor corrections, but otherwise looks good

2022-09-15 17:14 UTC, AgusArdizzone commented
I uploaded the requested changes 😄

2022-09-16 04:51 UTC, merged

2022-09-16 04:53 UTC, lars-berger commented
Great, looks good 👌

2022-10-13 09:11 UTC, lars-berger commented
Took a while longer than expected, but this is now in the [latest release](https://github.com/lars-berger/GlazeWM/releases) 👍