feat: add command move workspace to monitor (#50)
lars-berger/GlazeWM pull request #179
Opened 2022-11-27 15:24 UTC by kuznetsovvj

2022-11-27 16:40 UTC, lars-berger requested changes

2022-11-27 16:40 UTC, lars-berger commented on GlazeWM.Domain/DependencyInjection.cs
> +      services.AddSingleton<ICommandHandler<MoveWorkspaceToMonitorCommand>, MoveWorkspaceToMonitorHandler>();
`MoveWorkspaceInDirectionCommand` sounds a bit better i think, so it's consistent with `FocusInDirectionCommand`

2022-11-27 16:40 UTC, lars-berger commented on GlazeWM.Domain/Workspaces/CommandHandlers/MoveWorkspaceToMonitorHandler.cs
> +
Need to redraw after moving the container
```csharp
_bus.Invoke(new RedrawContainersCommand());
```

2022-11-27 16:40 UTC, lars-berger commented on GlazeWM.Domain/Workspaces/CommandHandlers/MoveWorkspaceToMonitorHandler.cs
> +      }
Need to update "floating placement" of windows
```csharp
// Update floating placements since the windows have to cross monitors.
foreach (var window in workspace.Descendants.OfType<Window>())
{
  window.FloatingPlacement =
    window.FloatingPlacement.TranslateToCenter(targetMonitor.DisplayedWorkspace.ToRect());
}
```

2022-11-28 19:27 UTC, kuznetsovvj commented on GlazeWM.Domain/DependencyInjection.cs
> +      services.AddSingleton<ICommandHandler<MoveWorkspaceToMonitorCommand>, MoveWorkspaceToMonitorHandler>();
renamed to `MoveWorkspaceInDirectionCommand`/`MoveWorkspaceInDirection`

2022-12-05 16:08 UTC, merged